### ISSUE TITLE
Cannot use focusEntity 2.2.3 with Xcode 13-Beta2

### ISSUE THREAD

**Issue by natchanonSCG** [maxxfrazer/FocusEntity#23] opened 2021-06-25 05:54 UTC
dyld: Library not loaded: /System/Library/Frameworks/RealityFoundation.framework/RealityFoundation
  Referenced from: /private/var/containers/Bundle/Application/8D110FAF-932D-4910-BCE9-169EE48D339E/testAR.app/testAR
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/usr/lib/libMTLCapture.dylib

**Environment:**
 - iOS Version - 13
 - Device Information - iPAD 2020
 - macOS Version - 11.3.1 (20E241)
 - Xcode Version - 13 Beta 2

**Comment by natchanonSCG** [comment] 2021-06-25 06:39
I was able to fix it by adding Reality.Foundation.framework in Frameworks, Libraries, and Embedded Content.

Then changed Build Phases of RealityFoundation.framework to "Optional" in Link Binary With Libraries

<img width="1117" alt="Screen Shot 2564-06-25 at 13 35 11" src="https://user-images.githubusercontent.com/85864453/123381446-f1a9c300-d5ba-11eb-88df-cbcd570cf46c.png">

<img width="1156" alt="Screen Shot 2564-06-25 at 13 37 17" src="https://user-images.githubusercontent.com/85864453/123381239-a98aa080-d5ba-11eb-8f68-ce92e55ba3eb.png">

**Comment by maxxfrazer** [comment] 2021-06-25 08:04
i believe this is a bug from the beta, we shouldn't even see RealityFoundation. thanks for finding a fix for beta users though!
let's see if this issue persists through the future beta versions

**Comment by ralfebert** [comment] 2021-07-26 18:27
Still happening in beta 3.
Did anyone file a FB already?

**Comment by maxxfrazer** [comment] 2021-07-26 19:20
I filed a FB about the RealityFoundation import appearing a while ago. But I just tried adding this package to a temporary project and didn't have the issue you're describing:
![Screenshot 2021-07-26 at 20 17 46](https://user-images.githubusercontent.com/5754073/127046216-cbe9e8eb-4753-40bd-9a43-d3403b767678.png)
![Screenshot 2021-07-26 at 20 18 32](https://user-images.githubusercontent.com/5754073/127046223-825929ee-21b7-467d-8629-f0699915ce3a.png)

**Comment by t2** [comment] 2021-08-19 12:56
@maxxfrazer I am seeing the error only when I try and run on device. Build is fine.

**Comment by maxxfrazer** [comment] 2021-08-24 08:25
I'm going to close this issue, as I cannot reproduce locally, so am assuming it's working fine now. Please leave a comment if this is persisting for you!

**Comment by ralfebert** [comment] 2021-09-23 16:52
Still happening with Xcode 13.0 final (13A233) for me

**Comment by maxxfrazer** [comment] 2021-10-14 12:16
I just made a new project with Xcode 13.0 (13A233), added FocusEntity and it is building + running fine on my phone.

All I changed was what can be seen in this file + camera usage description.

Is there anything else that could be different about your setup?
Is this error message appearing on build?
Have you tried to clean the build folder etc?

<img width="1170" alt="Screenshot 2021-10-14 at 14 14 01" src="https://user-images.githubusercontent.com/5754073/137315252-4a991079-ca31-4b22-9a3f-383eb7472042.png">

**Comment by maxxfrazer** [comment] 2021-10-25 07:44
I can't get this to reproduce locally, so am going to have to close this unless there are some consistently reproducible steps from a clean project.

**Comment by maxxfrazer** [comment] 2021-11-09 16:45
OK I've found a device that happens on! on an iPhone X.

I'll do some testing with it, will try come up with a solution that won't need manual changing of build phases

**Comment by maxxfrazer** [comment] 2022-02-26 19:17
Assuming this is all good new, closing!

**Closed as completed by maxxfrazer** 2022-02-26 19:17 UTC
Labels: bug
